version: "3.8"
services:
  caddy:
    image: caddy:2
    container_name: rose2-caddy-rose
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - youtaab-network
      - rose-network

volumes:
  caddy-data:
  caddy-config:

networks:
  youtaab-network:
    external: true
  rose-network:
    external: true
