version: '3.8'
services:
  app:
    build: .
    ports:
      - "3002:3000"  # Map to port 3002 to avoid conflicts
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
